"""
Curated source registry for SENTINEL ingestion.

The goal is not only to list feeds, but to encode how the pipeline should
treat them:

- `tier`: relative trust / value for event detection
- `role`: detection / verification / official / enrichment
- `policy`: whether lawful full-text extraction is allowed
- `fetch_limit`: per-feed depth override
- `archive_base`: optional WordPress JSON endpoint for historical backfill
"""

from __future__ import annotations

from query_lexicon import build_google_news_terms


def gnews_site_feed(
    site: str,
    terms: str,
    lang: str = "es-419",
    gl: str = "US",
    ceid: str = "US:es-419",
) -> str:
    query = f"site:{site}+({terms})"
    return f"https://news.google.com/rss/search?q={query}&hl={lang}&gl={gl}&ceid={ceid}"


def gnews_family_feed(
    site: str,
    family_names: tuple[str, ...] | list[str],
    *,
    language: str = "es",
    countries: tuple[str, ...] | list[str] | None = None,
    lang: str = "es-419",
    gl: str = "US",
    ceid: str = "US:es-419",
) -> str:
    terms = build_google_news_terms(
        family_names,
        language=language,
        include_countries=countries,
    )
    return gnews_site_feed(site, terms, lang=lang, gl=gl, ceid=ceid)


def feed(
    name: str,
    url: str,
    category: str,
    countries: list[str],
    *,
    tier: int,
    role: str,
    policy: str = "public_metadata",
    languages: tuple[str, ...] = ("es",),
    fetch_limit: int = 20,
    backfill_fetch_limit: int | None = None,
    quality_weight: float = 0.5,
    fetch_full_text: bool = False,
    archive_base: str | None = None,
    source_method: str = "rss",
) -> dict:
    return {
        "name": name,
        "url": url,
        "category": category,
        "countries": countries,
        "tier": tier,
        "role": role,
        "policy": policy,
        "languages": list(languages),
        "fetch_limit": fetch_limit,
        "backfill_fetch_limit": backfill_fetch_limit,
        "quality_weight": quality_weight,
        "fetch_full_text": fetch_full_text,
        "archive_base": archive_base,
        "source_method": source_method,
    }


RSS_FEEDS = [
    # Regional investigative / security
    feed(
        "InSight Crime",
        "https://insightcrime.org/feed/",
        "investigative_security",
        ["Regional"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("en", "es"),
        fetch_limit=30,
        backfill_fetch_limit=80,
        quality_weight=0.96,
        fetch_full_text=True,
        archive_base="https://insightcrime.org/wp-json/wp/v2/posts",
    ),
    feed(
        "CONNECTAS",
        "https://www.connectas.org/feed/",
        "investigative_security",
        ["Regional"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=18,
        backfill_fetch_limit=48,
        quality_weight=0.9,
        fetch_full_text=True,
    ),
    feed(
        "Crisis Group",
        "https://www.crisisgroup.org/rss",
        "conflict_analysis",
        ["Regional"],
        tier=2,
        role="enrichment",
        policy="public_fulltext",
        languages=("en",),
        fetch_limit=16,
        quality_weight=0.88,
        fetch_full_text=True,
    ),
    feed(
        "Americas Quarterly",
        "https://americasquarterly.org/feed/",
        "policy_analysis",
        ["Regional"],
        tier=3,
        role="enrichment",
        policy="public_fulltext",
        languages=("en",),
        fetch_limit=12,
        quality_weight=0.74,
        fetch_full_text=True,
        archive_base="https://americasquarterly.org/wp-json/wp/v2/posts",
    ),
    feed(
        "NACLA",
        gnews_family_feed(
            "nacla.org",
            ["state_repression_and_exceptional_rule", "organized_crime_and_transnational_security"],
            language="en",
            countries=("Mexico", "Colombia", "Venezuela", "El Salvador", "Brazil"),
            lang="en-US",
            ceid="US:en",
        ),
        "policy_analysis",
        ["Regional"],
        tier=3,
        role="enrichment",
        policy="public_metadata",
        languages=("en",),
        quality_weight=0.72,
        archive_base="https://nacla.org/wp-json/wp/v2/posts",
        source_method="google_news_rss",
    ),

    # Wire / verification
    feed(
        "Reuters LatAm",
        gnews_family_feed(
            "reuters.com",
            ["armed_conflict_and_territorial_control", "state_repression_and_exceptional_rule", "external_security_support_and_alignment"],
            language="en",
            countries=("Mexico", "Colombia", "Venezuela", "Brazil"),
            lang="en-US",
            ceid="US:en",
        ),
        "wire",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_metadata",
        languages=("en", "es"),
        fetch_limit=20,
        quality_weight=0.86,
        source_method="google_news_rss",
    ),
    feed(
        "AP LatAm",
        gnews_family_feed(
            "apnews.com",
            ["armed_conflict_and_territorial_control", "organized_crime_and_transnational_security", "state_repression_and_exceptional_rule"],
            language="en",
            countries=("Mexico", "Colombia", "Venezuela", "Brazil", "Ecuador", "Haiti"),
            lang="en-US",
            ceid="US:en",
        ),
        "wire",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_metadata",
        languages=("en", "es"),
        fetch_limit=20,
        quality_weight=0.84,
        source_method="google_news_rss",
    ),
    feed(
        "AFP LatAm",
        gnews_site_feed("afp.com", "latin+america+OR+military+OR+security+OR+coup+OR+protest+OR+organized+crime"),
        "wire",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_metadata",
        languages=("en", "es", "fr"),
        fetch_limit=20,
        quality_weight=0.82,
        source_method="google_news_rss",
    ),
    feed(
        "EFE",
        gnews_family_feed(
            "efe.com",
            ["armed_conflict_and_territorial_control", "organized_crime_and_transnational_security", "coup_and_command_break"],
            language="es",
            countries=("Mexico", "Colombia", "Venezuela", "Brazil", "Ecuador", "Peru"),
        ),
        "wire",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_metadata",
        languages=("es",),
        fetch_limit=20,
        quality_weight=0.82,
        source_method="google_news_rss",
    ),
    feed(
        "BBC Americas",
        "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
        "general_news",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("en",),
        fetch_limit=20,
        quality_weight=0.82,
        fetch_full_text=True,
    ),
    feed(
        "BBC Mundo",
        "https://feeds.bbci.co.uk/mundo/rss.xml",
        "general_news",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=20,
        quality_weight=0.82,
        fetch_full_text=True,
    ),
    feed(
        "The Guardian LatAm",
        "https://www.theguardian.com/world/americas/rss",
        "general_news",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("en",),
        fetch_limit=20,
        quality_weight=0.78,
        fetch_full_text=True,
    ),
    feed(
        "El País América",
        "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/america/portada",
        "general_news",
        ["Regional"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=20,
        quality_weight=0.8,
        fetch_full_text=True,
    ),

    # Regional / specialist context
    feed(
        "Infodefensa",
        gnews_family_feed(
            "infodefensa.com",
            ["external_security_support_and_alignment", "military_exercises_and_force_posture", "procurement_and_arms"],
            language="es",
            countries=("Brazil", "Colombia", "Mexico", "Argentina", "Peru"),
        ),
        "defense_specialist",
        ["Regional"],
        tier=2,
        role="detection",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.76,
        source_method="google_news_rss",
    ),
    feed(
        "Zona Militar",
        gnews_family_feed(
            "zona-militar.com",
            ["external_security_support_and_alignment", "military_exercises_and_force_posture", "procurement_and_arms"],
            language="es",
            countries=("Argentina", "Brazil", "Chile", "Peru"),
        ),
        "defense_specialist",
        ["Regional"],
        tier=2,
        role="detection",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.76,
        source_method="google_news_rss",
    ),
    feed(
        "Human Rights Watch",
        gnews_family_feed(
            "hrw.org",
            ["state_repression_and_exceptional_rule", "corruption_capture_and_judicial_pressure"],
            language="en",
            countries=("Colombia", "Mexico", "Venezuela", "El Salvador", "Brazil", "Haiti"),
            lang="en-US",
            ceid="US:en",
        ),
        "human_rights_monitor",
        ["Regional"],
        tier=2,
        role="enrichment",
        policy="public_metadata",
        languages=("en", "es"),
        quality_weight=0.8,
        source_method="google_news_rss",
    ),
    feed(
        "Amnesty International",
        gnews_family_feed(
            "amnesty.org",
            ["state_repression_and_exceptional_rule", "corruption_capture_and_judicial_pressure"],
            language="en",
            countries=("Colombia", "Mexico", "Venezuela", "El Salvador", "Brazil", "Haiti"),
            lang="en-US",
            ceid="US:en",
        ),
        "human_rights_monitor",
        ["Regional"],
        tier=2,
        role="enrichment",
        policy="public_metadata",
        languages=("en", "es"),
        quality_weight=0.78,
        source_method="google_news_rss",
    ),
    feed(
        "SOUTHCOM",
        gnews_family_feed(
            "southcom.mil",
            ["external_security_support_and_alignment", "military_exercises_and_force_posture"],
            language="en",
            countries=("Colombia", "Brazil", "Peru", "Ecuador", "Panama"),
            lang="en-US",
            ceid="US:en",
        ),
        "official",
        ["Regional"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("en",),
        quality_weight=0.68,
        source_method="google_news_rss",
    ),

    # Colombia
    feed(
        "El Tiempo Colombia",
        "https://www.eltiempo.com/rss/politica.xml",
        "general_news",
        ["Colombia"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=20,
        quality_weight=0.78,
        fetch_full_text=True,
    ),
    feed(
        "La Silla Vacía",
        "https://www.lasillavacia.com/feed/",
        "investigative_security",
        ["Colombia"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=18,
        quality_weight=0.92,
        fetch_full_text=True,
    ),
    feed(
        "VerdadAbierta",
        "https://verdadabierta.com/feed/",
        "investigative_security",
        ["Colombia"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=18,
        quality_weight=0.92,
        fetch_full_text=True,
    ),
    feed(
        "Vorágine",
        "https://voragine.co/feed/",
        "investigative_security",
        ["Colombia"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=15,
        quality_weight=0.88,
        fetch_full_text=True,
    ),
    feed(
        "Semana Colombia",
        gnews_family_feed(
            "semana.com",
            ["armed_conflict_and_territorial_control", "organized_crime_and_transnational_security"],
            language="es",
            countries=("Colombia",),
        ),
        "general_news",
        ["Colombia"],
        tier=3,
        role="verification",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.64,
        source_method="google_news_rss",
    ),
    feed(
        "Colombia Mindefensa",
        gnews_family_feed(
            "mindefensa.gov.co",
            ["armed_conflict_and_territorial_control", "external_security_support_and_alignment"],
            language="es",
            countries=("Colombia",),
        ),
        "official",
        ["Colombia"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.6,
        source_method="google_news_rss",
    ),

    # Mexico
    feed(
        "Animal Político Seguridad",
        gnews_family_feed(
            "animalpolitico.com",
            ["organized_crime_and_transnational_security", "criminal_violence_and_illicit_economies", "state_repression_and_exceptional_rule"],
            language="es",
            countries=("Mexico",),
        ),
        "investigative_security",
        ["Mexico"],
        tier=1,
        role="detection",
        policy="public_metadata",
        languages=("es",),
        fetch_limit=18,
        quality_weight=0.9,
        source_method="google_news_rss",
    ),
    feed(
        "Zeta Tijuana",
        "https://zetatijuana.com/feed/",
        "investigative_security",
        ["Mexico"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=18,
        quality_weight=0.9,
        fetch_full_text=True,
    ),
    feed(
        "Mexico SEDENA",
        gnews_family_feed(
            "gob.mx",
            ["external_security_support_and_alignment", "state_repression_and_exceptional_rule", "organized_crime_and_transnational_security"],
            language="es",
            countries=("Mexico",),
        ),
        "official",
        ["Mexico"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.58,
        source_method="google_news_rss",
    ),

    # Venezuela
    feed(
        "Runrun.es",
        "https://runrun.es/feed/",
        "investigative_security",
        ["Venezuela"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=20,
        backfill_fetch_limit=64,
        quality_weight=0.92,
        fetch_full_text=True,
    ),
    feed(
        "Efecto Cocuyo",
        "https://efectococuyo.com/feed/",
        "investigative_security",
        ["Venezuela"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=20,
        backfill_fetch_limit=64,
        quality_weight=0.92,
        fetch_full_text=True,
    ),
    feed(
        "Armando.info",
        "https://armando.info/feed/",
        "investigative_security",
        ["Venezuela"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=16,
        backfill_fetch_limit=48,
        quality_weight=0.94,
        fetch_full_text=True,
    ),
    feed(
        "TalCual",
        "https://talcualdigital.com/feed/",
        "general_news",
        ["Venezuela"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=18,
        quality_weight=0.8,
        fetch_full_text=True,
    ),
    feed(
        "El Nacional Venezuela",
        "https://www.elnacional.com/feed/",
        "general_news",
        ["Venezuela"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=18,
        quality_weight=0.76,
        fetch_full_text=True,
    ),

    # Peru
    feed(
        "IDL-Reporteros",
        "https://www.idl-reporteros.pe/feed/",
        "investigative_security",
        ["Peru"],
        tier=1,
        role="detection",
        policy="public_fulltext",
        languages=("es",),
        fetch_limit=16,
        backfill_fetch_limit=48,
        quality_weight=0.92,
        fetch_full_text=True,
    ),
    feed(
        "Peru MINDEF",
        gnews_family_feed(
            "gob.pe",
            ["external_security_support_and_alignment", "armed_conflict_and_territorial_control"],
            language="es",
            countries=("Peru",),
        ),
        "official",
        ["Peru"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.56,
        source_method="google_news_rss",
    ),

    # El Salvador / Central America
    feed(
        "El Faro",
        gnews_family_feed(
            "elfaro.net",
            ["organized_crime_and_transnational_security", "state_repression_and_exceptional_rule", "criminal_violence_and_illicit_economies"],
            language="es",
            countries=("El Salvador",),
        ),
        "investigative_security",
        ["El Salvador"],
        tier=1,
        role="detection",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.92,
        source_method="google_news_rss",
    ),
    feed(
        "Honduras SEDENA",
        gnews_family_feed(
            "sedena.gob.hn",
            ["external_security_support_and_alignment", "organized_crime_and_transnational_security"],
            language="es",
            countries=("Honduras",),
        ),
        "official",
        ["Honduras"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.54,
        source_method="google_news_rss",
    ),
    feed(
        "Guatemala MINDEF",
        gnews_family_feed(
            "guatemala.gob.gt",
            ["external_security_support_and_alignment", "organized_crime_and_transnational_security"],
            language="es",
            countries=("Guatemala",),
        ),
        "official",
        ["Guatemala"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.54,
        source_method="google_news_rss",
    ),

    # Southern cone / broader
    feed(
        "La Nación Argentina",
        gnews_family_feed(
            "lanacion.com.ar",
            ["state_repression_and_exceptional_rule", "external_security_support_and_alignment"],
            language="es",
            countries=("Argentina",),
        ),
        "general_news",
        ["Argentina"],
        tier=2,
        role="verification",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.74,
        source_method="google_news_rss",
    ),
    feed(
        "Folha de S.Paulo",
        "https://feeds.folha.uol.com.br/poder/rss091.xml",
        "general_news",
        ["Brazil"],
        tier=2,
        role="verification",
        policy="public_fulltext",
        languages=("pt",),
        fetch_limit=18,
        quality_weight=0.78,
        fetch_full_text=True,
    ),
    feed(
        "Agência Brasil",
        gnews_family_feed(
            "agenciabrasil.ebc.com.br",
            ["organized_crime_and_transnational_security", "external_security_support_and_alignment", "state_repression_and_exceptional_rule"],
            language="pt",
            countries=("Brazil",),
            lang="pt-BR",
            ceid="BR:pt-419",
        ),
        "official_public_media",
        ["Brazil"],
        tier=2,
        role="detection",
        policy="public_metadata",
        languages=("pt",),
        quality_weight=0.74,
        source_method="google_news_rss",
    ),
    feed(
        "Argentina Defensa",
        gnews_family_feed(
            "argentina.gob.ar",
            ["external_security_support_and_alignment", "military_exercises_and_force_posture"],
            language="es",
            countries=("Argentina",),
        ),
        "official",
        ["Argentina"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.56,
        source_method="google_news_rss",
    ),
    feed(
        "Uruguay Defensa",
        gnews_family_feed(
            "gub.uy",
            ["external_security_support_and_alignment", "military_exercises_and_force_posture"],
            language="es",
            countries=("Uruguay",),
        ),
        "official",
        ["Uruguay"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.56,
        source_method="google_news_rss",
    ),
    feed(
        "Bolivia Defensa",
        gnews_family_feed(
            "mindef.gob.bo",
            ["external_security_support_and_alignment", "armed_conflict_and_territorial_control"],
            language="es",
            countries=("Bolivia",),
        ),
        "official",
        ["Bolivia"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.54,
        source_method="google_news_rss",
    ),
    feed(
        "Dominican Republic MIDE",
        gnews_family_feed(
            "mide.gob.do",
            ["external_security_support_and_alignment", "organized_crime_and_transnational_security"],
            language="es",
            countries=("Dominican Republic",),
        ),
        "official",
        ["Dominican Republic"],
        tier=3,
        role="official",
        policy="public_metadata",
        languages=("es",),
        quality_weight=0.54,
        source_method="google_news_rss",
    ),
]


ARCHIVE_SOURCES = [item for item in RSS_FEEDS if item.get("archive_base")]
